# Setup
title:               Popoory67
tagline:             'A developer site'
description:         'Postings written by <a href="https://www.linkedin.com/in/bozeury/" target="_blank">@popoory67</a>.'
url:                 https://popoory67.github.io/
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              popoory67
  url:               https://www.linkedin.com/in/bozeury/
  email:             bozeury@gmail.com

# Gems
plugins:
  - jekyll-paginate

exclude:
  - README.md
  - LICENSE.md
  - node_modules
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock

# Custom vars
site:
version:             1.1.0
google_analytics_id: #UA-XXXX-Y

# Collections
collections:
  pages:
    permalink: /:name/
    output: true
    
# Navigation (2nd level links supported)
nav:
  Home:
    - '/'
  Jekyll:
    - '/jekyll/'
  Programming:
    - '/programming/'
    - { Graphics: '/graphics/' }
    - { Cpp: '/cpp/' }
